### ISSUE TITLE
Apply rice

### ISSUE THREAD

**Issue by 3dgoose** [harshhhdev/dotfiles#1]
Hoya. I'm a beginner in rice world. Admitting I have copied all those files in ~/.config, how to add a background and how to apply theme ? Like, transform my desktop like in the images ? I use normal Arch linux, not arch craft.

**Comment by haaarshsingh** [comment]
well, you can't copy the 1:1 and expect them to work unless you have the same apps and programs installed. do you have all the apps and programs installed that i've listed in the readme?
